# Generated by Django 3.2.7 on 2021-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='sex',
            field=models.CharField(blank=True, choices=[{'Male', 'M'}, {'F', 'Female'}], max_length=6),
        ),
    ]
